<?php

/**
 *  @file
 *  Configuration - load
 *  
 *  @path /system/setup/config/load
 */

$head_page_title = "<i class='icon-download-alt'></i> Save configuration to files";

//      Confirmation
if ( empty( $_GET[ 'yes' ]) && empty( $_POST[ 'poormans-submit-flag' ]))
{
    //      @todo
    $content .= "Todo 2014/06/22 20:31:56";
}

//      Execution
else
{
    //      @todo
    $content .= "Todo 2014/06/22 20:31:56";
}


