<?php

/**
 *  @file
 *  Template Fragment - Javascript at the bottom of HTML page, before </body>
 *  (used both in page.tpl.php and iframe.tml.php)
 */

/*
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="<?php print $base_path; ?>theme/_assets/vendor/jquery/jquery-1.9.1.min.js"><\/script>')</script>
*/
?>
    <script src="<?php print $base_path; ?>theme/_assets/js/main.js"></script>
