<?php

/**
 *  @file
 *  Template Fragment - Assets loaded in <head>
 *  (used both in page.tpl.php and iframe.tml.php)
 */

/*      Vendor JS example :
<!--[if lt IE 9]>
<script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<script>window.html5 || document.write('<script src="<?php print $base_path; ?>theme/_assets/vendor/html5shiv/html5shiv.js"><\/script>')</script>
<![endif]-->
*/

?>
    <link rel="shortcut icon" href="<?php print $base_path; ?>favicon.ico">
    <link rel="stylesheet" href="<?php print $base_path; ?>theme/_assets/css/main.css">
