<?php

/**
 *  @file
 *  Template Fragment - Assets loaded in <head>
 *  (used both in page.tpl.php and iframe.tml.php)
 */

?>
    <link rel="shortcut icon" href="<?php print $base_path; ?>favicon.ico">
    
    <!--
    <link rel="stylesheet" href="<?php print $base_path; ?>theme/css/vendor/bootstrap.min.css">
    <link rel="stylesheet" href="<?php print $base_path; ?>theme/css/vendor/flatly.css">
    <link rel="stylesheet" href="<?php print $base_path; ?>theme/css/vendor/united.css">
    <link rel="stylesheet" href="<?php print $base_path; ?>theme/css/vendor/metro.css">
    -->
    <link rel="stylesheet" href="<?php print $base_path; ?>theme/css/vendor/spacelab.css">
    <link rel="stylesheet" href="<?php print $base_path; ?>theme/css/vendor/bootstrap-responsive.min.css">
    
    <link rel="stylesheet" href="<?php print $base_path; ?>theme/css/vendor/font-awesome.min.css">
    <link rel="stylesheet" href="<?php print $base_path; ?>theme/css/vendor/DT_bootstrap.css">
    <link rel="stylesheet" href="<?php print $base_path; ?>theme/css/vendor/github.css">
    <link rel="stylesheet" href="<?php print $base_path; ?>theme/css/vendor/chosen.min.css">
    
    <!--[if lt IE 8]>
    <link rel="stylesheet" href="<?php print $base_path; ?>theme/css/vendor/font-awesome-ie7.min.css">
    <![endif]-->
    
    <link rel="stylesheet" href="<?php print $base_path; ?>theme/css/main.css">
    
    <!--[if lt IE 9]>
    <script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <script>window.html5 || document.write('<script src="<?php print $base_path; ?>theme/js/vendor/html5shiv.js"><\/script>')</script>
    <![endif]-->
